CREATE TABLE "usuario" (
	"id_usuario" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(40) NOT NULL,
	"mail" VARCHAR(40) NOT NULL,
	"fechaRegistro" DATE NOT NULL,
	PRIMARY KEY("id_usuario")
);




CREATE TABLE "publicacion" (
	"id_publicacion" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"titulo" VARCHAR(100) NOT NULL,
	"contenido" TEXT NOT NULL,
	"creacion" DATE NOT NULL,
	"id_usuario" INTEGER NOT NULL,
	PRIMARY KEY("id_publicacion")
);



ALTER TABLE "publicacion"
ADD FOREIGN KEY("id_usuario") REFERENCES "usuario"("id_usuario")
ON UPDATE NO ACTION ON DELETE NO ACTION;